/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_page1 (void);
GtkWidget* create_page2 (void);
GtkWidget* create_page3 (void);
GtkWidget* create_page4 (void);
GtkWidget* create_page5 (void);
GtkWidget* create_page6 (void);
GtkWidget* create_page7 (void);
GtkWidget* create_Affichagehamza (void);
GtkWidget* create_Ajouthamza (void);
GtkWidget* create_Modifhamza (void);
GtkWidget* create_Supprimerhamza (void);
GtkWidget* create_NombreReclParL (void);
GtkWidget* create_AfficheNbreReclamation (void);
GtkWidget* create_MenuDeChoix (void);
GtkWidget* create_aff_th (void);
GtkWidget* create_sup_th (void);
GtkWidget* create_mdf_th (void);
GtkWidget* create_aj_th (void);
GtkWidget* create_page20 (void);
GtkWidget* create_interface (void);
GtkWidget* create_window_supprimer (void);
GtkWidget* create_window_ajouter (void);
GtkWidget* create_window_chercher (void);
GtkWidget* create_window_modifier (void);
GtkWidget* create_window_afficher (void);
GtkWidget* create_interface1 (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_modifier (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_int1 (void);
GtkWidget* create_supDialog (void);
GtkWidget* create_critereRec (void);
GtkWidget* create_affichage_ob (void);
GtkWidget* create_ajout_observation (void);
GtkWidget* create_modifier_obs (void);
GtkWidget* create_pageStatSarra (void);
GtkWidget* create_treeViewScore (void);
